config/routes.rb
Video::Application.routes.draw do
  
  root :to => 'main#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :episodes
  get 'episodes/tags/:tag', to: 'episodes#index', as: :tag
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessible :description, :name, :notes, :permalink, :position, :published_at, :tag_list
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  respond_to :html
  
  def index
    products_per_page = 10
    if params[:tag]
      @episodes = Episode.tagged_with(params[:tag]).page(params[:page]).per(products_per_page)
    else
      @episodes = Episode.page(params[:page]).per(products_per_page)
    end
  end
  
  def show
    @episode = Episode.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def tags_menu
    Proc.new do |primary|
      primary.dom_class = 'sidebar_menu'
      tag_cloud Episode.tag_counts, %w[s m l] do |tag, css_class|
        primary.item "tag_#{tag.id}", tag.name, tag_path(tag.name)
      end
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/episodes/index.html.erb
<div class="grid_9">
  <div class="episodes">
    <% if !@episodes.blank? %>
      <% for episode in @episodes %>
      <div class="episode">
        <div class="image">
          <%= link_to image_tag("/assets/episodes/#{episode.permalink}/#{episode.permalink}.png", size: '200x125', class: 'thumbnail'), episode %>
        </div>
        <div class="desc">
          <h3><%= link_to episode.name, episode %></h3>
          <div class="description"><%= raw episode.description %></div>
          <div class="tags">Tags: <%= raw episode.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></div>
        </div>
      </div>
      <div class="clear"></div>
      <% end %>
      <%= paginate @episodes %>
    <% else %>
      episodes not found
    <% end %>
  </div>
</div>
<div class="grid_3">
  <div id="tag_cloud">
    <%= render_navigation &tags_menu %>
  </div>
</div>

app/views/episodes/show.html.erb
<div class="grid_12">
  <div class="episode">
    <div class="video">
      <video poster="/assets/default_video.jpg" controls class="thumbnail" style="">
        <source src="/assets/episodes/<%= @episode.permalink %>/<%= @episode.permalink %>.mp4" type='video/mp4; codecs="avc1.4D401E, mp4a.40.2"'/>
        <p>This is fallback content</p>
      </video>
    </div>
    <div class="desc">
      <div class="panel">
        <h3><%= @episode.name %></h3>
        <div class="notes"><%= raw @episode.notes %></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="grid_12 top">
        <h1 id="logo" class="icon-play-circle"> Video</h1>
      </div>
      <div class="clear"></div>
      <div class="grid_12">
        <ul class="main_menu">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Episodes", episodes_path %></li>
          <li><%= link_to "link text...", '#' %></li>
          <li><%= link_to "link text...", '#' %></li>
          <li><%= link_to "link text...", '#' %></li>
          <li class="search"><center>Search: <input type="search" name="search" value="" id="search"></center></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="yield">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <div class="footer">
    <div class="container">
      <div class="grid_12">
        <hr />
        <p>Eddie Fisher 12/05/2013</p>
      </div>
    </div>
  </div>
</body>
</html>

app/views/main/index.html.erb
<div class="grid_12">
  main
</div>